# Generated by Django 5.2.4 on 2025-08-22 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblCategoria',
            fields=[
                ('categoria_id', models.AutoField(primary_key=True, serialize=False)),
                ('categoria_nombre', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'tbl_categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TblCurso',
            fields=[
                ('curso_id', models.AutoField(primary_key=True, serialize=False)),
                ('curso_titulo', models.CharField(max_length=255)),
                ('curso_descripcion', models.TextField()),
            ],
            options={
                'db_table': 'tbl_curso',
                'managed': False,
            },
        ),
    ]
