# Generated by Django 5.2.4 on 2025-08-22 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tblcategoria',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='tblcurso',
            options={'managed': True},
        ),
    ]
